# Generated by Django 5.0.4 on 2026-04-01 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField()),
                ('sms_type', models.CharField(choices=[('payment_reminder', "To'lov eslatma"), ('debt_reminder', 'Qarz eslatma'), ('manual', "Qo'lda yuborilgan"), ('welcome', 'Xush kelibsiz'), ('custom', 'Boshqa')], default='custom', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('delivered', 'Yetkazildi'), ('failed', 'Xato')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
            ],
            options={
                'verbose_name': 'SMS tarixi',
                'verbose_name_plural': 'SMS tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
