# Generated by Django 5.0.4 on 2026-04-01 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True)),
                ('duration_months', models.PositiveIntegerField(default=3, verbose_name='Davomiyligi (oy)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma %')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Guruh a'zoligi",
                'verbose_name_plural': "Guruh a'zoliklari",
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('day_type', models.CharField(choices=[('odd', 'Toq kunlar (Du,Cho,Ju)'), ('even', 'Juft kunlar (Se,Pa,Sha)'), ('daily', 'Har kuni'), ('weekend', 'Dam olish kunlari')], default='odd', max_length=20)),
                ('start_time', models.TimeField(verbose_name='Dars boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Dars tugash vaqti')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Oylik to'lov (UZS)")),
                ('payment_day', models.PositiveIntegerField(default=1, help_text="1-28 oralig'ida", verbose_name="Har oyning necha-sanasida to'lov")),
                ('start_date', models.DateField(verbose_name='Guruh boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_students', models.PositiveIntegerField(default=15)),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='groups.course')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['name'],
            },
        ),
    ]
