# Generated by Django 5.0.4 on 2026-04-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_time',
            field=models.TimeField(default='18:00:00', verbose_name='Dars tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_time',
            field=models.TimeField(default='16:00:00', verbose_name='Dars boshlanish vaqti'),
        ),
    ]
