# Generated by Django 5.0.4 on 2026-04-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
    ]
